name: Deploy Back Blogex

on:
  push:
    branches:
      - master

concurrency:
  group: blogex-production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest

    steps:
      - name: Configurar SSH
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          mkdir -p ~/.ssh
      
          echo "$VPS_SSH_KEY" > ~/.ssh/blogex_key
          chmod 600 ~/.ssh/blogex_key
      
          ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

      - name: Executar deploy na VPS
        run: |
          ssh -i ~/.ssh/blogex_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /var/www/blogex && ./deploy.sh"
